const sampleListings = [
{
  title: "Luxury Houseboat on Dal Lake",
  description: "Experience the charm of Kashmir in a handcrafted houseboat with lake views and traditional interiors.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
  },
  price: 2400,
  location: "Srinagar",
  country: "India",
  category: ["Boats", "Trending"],
},
{
  title: "Glass Igloo Under the Northern Lights",
  description: "Sleep beneath the Aurora Borealis in a heated glass igloo.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=60",
  },
  price: 4800,
  location: "Lapland",
  country: "Finland",
  category: ["Arctic", "Trending"],
},
{
  title: "Luxury Dome Retreat",
  description: "A modern geodesic dome surrounded by mountains and forests.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=60",
  },
  price: 2100,
  location: "Reykjavik",
  country: "Iceland",
  category: ["Domes", "Mountain"],
},
{
  title: "Santorini Cave House",
  description: "Traditional cave home with stunning sea views.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
  },
  price: 3200,
  location: "Santorini",
  country: "Greece",
  category: ["Rooms", "Trending"],
},
{
  title: "Luxury Vineyard Farm Stay",
  description: "Relax among vineyards with wine tasting and countryside views.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1465379944081-7f47de8d74ac?auto=format&fit=crop&w=800&q=60",
  },
  price: 2600,
  location: "Napa Valley",
  country: "United States",
  category: ["Farms", "Trending"],
},
{
  title: "Floating Villa in Bora Bora",
  description: "Overwater villa with private deck and turquoise lagoon.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=800&q=60",
  },
  price: 7200,
  location: "Bora Bora",
  country: "French Polynesia",
  category: ["Pools", "Trending"],
},
{
  title: "Black Forest Cabin",
  description: "Cozy wooden cabin in Germany's famous Black Forest.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=60",
  },
  price: 1800,
  location: "Black Forest",
  country: "Germany",
  category: ["Mountain", "Camping"],
},
{
  title: "Irish Castle Estate",
  description: "Live like royalty in a restored medieval castle.",
  image: {
    filename: "listingimage",
    url: "https://imgs.search.brave.com/T3ykoLyWWz9OWYFc1zrWVIstqsAzclMm3OO4OlLwPKM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/a2lscm9uYW5jYXN0/bGUuaWUvd3AtY29u/dGVudC91cGxvYWRz/LzIwMTcvMDQvZXh0/ZXJpb3ItZ2FsbGVy/eS01NzB4NDMwLmpw/Zw",
  },
  price: 5300,
  location: "Dublin",
  country: "Ireland",
  category: ["Castles", "Trending"],
},
{
  title: "Infinity Pool Villa",
  description: "Luxury villa overlooking Lake Pichola.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=60",
  },
  price: 2900,
  location: "Udaipur",
  country: "India",
  category: ["Pools", "Trending"],
},
{
  title: "Lakefront Glass Cabin",
  description: "Modern cabin with floor-to-ceiling lake views.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
  },
  price: 1900,
  location: "Queenstown",
  country: "New Zealand",
  category: ["Mountain", "Trending"],
},
{
  title: "Kyoto Traditional Ryokan",
  description: "Authentic Japanese inn with tatami rooms and hot springs.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=60",
  },
  price: 2100,
  location: "Kyoto",
  country: "Japan",
  category: ["Rooms", "Iconic Cities"],
},
{
  title: "Goa Beach Villa",
  description: "Private villa just steps away from the beach.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=60",
  },
  price: 1700,
  location: "Goa",
  country: "India",
  category: ["Pools", "Trending"],
},
{
  title: "Swiss Alpine Chalet",
  description: "Classic wooden chalet with breathtaking alpine scenery.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=60",
  },
  price: 3400,
  location: "Zermatt",
  country: "Switzerland",
  category: ["Mountain", "Trending"],
},
{
  title: "Venice Canal Apartment",
  description: "Stay beside Venice's beautiful canals.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=60",
  },
  price: 2300,
  location: "Venice",
  country: "Italy",
  category: ["Iconic Cities", "Rooms"],
},
{
  title: "Manali A-Frame Cabin",
  description: "Modern A-frame cabin surrounded by pine forests.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=60",
  },
  price: 1500,
  location: "Manali",
  country: "India",
  category: ["Mountain", "Camping"],
},
{
  title: "Dubai Sky Penthouse",
  description: "Luxury penthouse overlooking the Burj Khalifa skyline.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=800&q=60",
  },
  price: 5800,
  location: "Dubai",
  country: "United Arab Emirates",
  category: ["Rooms", "Trending"],
},
{
  title: "Moroccan Riad",
  description: "Traditional riad with colorful courtyards and rooftop views.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
  },
  price: 1900,
  location: "Marrakech",
  country: "Morocco",
  category: ["Rooms", "Trending"],
},
{
  title: "Norwegian Fjord Cabin",
  description: "Scenic cabin overlooking majestic fjords.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=60",
  },
  price: 2600,
  location: "Bergen",
  country: "Norway",
  category: ["Mountain", "Camping"],
},
{
  title: "Cappadocia Cave Hotel",
  description: "Unique cave suite with sunrise balloon views.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
  },
  price: 2400,
  location: "Cappadocia",
  country: "Turkey",
  category: ["Rooms", "Trending"],
},
{
  title: "Phuket Beach Resort",
  description: "Beachfront luxury resort with infinity pool and sea views.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=800&q=60",
  },
  price: 2800,
  location: "Phuket",
  country: "Thailand",
  category: ["Pools", "Trending"],
},
{
  title: "Paris Eiffel View Apartment",
  description: "Elegant apartment with a balcony overlooking the Eiffel Tower.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=60",
  },
  price: 3500,
  location: "Paris",
  country: "France",
  category: ["Iconic Cities", "Rooms"],
},
{
  title: "Kerala Backwater Houseboat",
  description: "Cruise through peaceful backwaters in a luxury houseboat with authentic Kerala cuisine.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
  },
  price: 1900,
  location: "Alleppey",
  country: "India",
  category: ["Boats", "Trending"],
},
{
  title: "Iceland Volcano Cabin",
  description: "Stay near volcanic landscapes with geothermal hot springs nearby.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=60",
  },
  price: 3100,
  location: "Vik",
  country: "Iceland",
  category: ["Mountain", "Trending"],
},
{
  title: "Barcelona Rooftop Loft",
  description: "Modern loft featuring a private rooftop terrace in the heart of Barcelona.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=60",
  },
  price: 2200,
  location: "Barcelona",
  country: "Spain",
  category: ["Iconic Cities", "Rooms"],
},
{
  title: "Amazon Rainforest Eco Lodge",
  description: "Reconnect with nature in a sustainable eco lodge deep inside the rainforest.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=60",
  },
  price: 1700,
  location: "Manaus",
  country: "Brazil",
  category: ["Camping", "Farms"],
},
{
  title: "Maldives Sunset Water Villa",
  description: "Luxury overwater villa with direct access to crystal-clear lagoons.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=800&q=60",
  },
  price: 7800,
  location: "Male",
  country: "Maldives",
  category: ["Pools", "Trending"],
},
{
  title: "Scottish Highland Cabin",
  description: "A peaceful wooden cabin surrounded by dramatic Highland scenery.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
  },
  price: 1700,
  location: "Inverness",
  country: "United Kingdom",
  category: ["Mountain", "Camping"],
},
{
  title: "Lisbon Heritage Apartment",
  description: "Beautiful apartment located in the colorful streets of old Lisbon.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=60",
  },
  price: 1800,
  location: "Lisbon",
  country: "Portugal",
  category: ["Iconic Cities", "Rooms"],
},
{
  title: "Desert Luxury Camp",
  description: "Enjoy luxury tents, camel rides, and unforgettable desert sunsets.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=60",
  },
  price: 2300,
  location: "Jaisalmer",
  country: "India",
  category: ["Camping", "Trending"],
},
{
  title: "Banff Lake Lodge",
  description: "A charming lodge overlooking turquoise alpine lakes.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=60",
  },
  price: 2400,
  location: "Banff",
  country: "Canada",
  category: ["Mountain", "Trending"],
},
{
  title: "Sydney Harbour Penthouse",
  description: "Luxury penthouse offering spectacular harbour and Opera House views.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=800&q=60",
  },
  price: 4300,
  location: "Sydney",
  country: "Australia",
  category: ["Iconic Cities", "Rooms"],
},
{
  title: "Alaskan Snow Cabin",
  description: "Cozy log cabin surrounded by snowy forests and frozen lakes.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=60",
  },
  price: 2600,
  location: "Anchorage",
  country: "United States",
  category: ["Arctic", "Mountain"],
},
{
  title: "Dutch Windmill Stay",
  description: "Spend the night inside a beautifully restored historic windmill.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800&q=60",
  },
  price: 2100,
  location: "Kinderdijk",
  country: "Netherlands",
  category: ["Rooms", "Trending"],
},
{
  title: "Bali Jungle Villa",
  description: "Private jungle villa featuring an infinity pool and tropical gardens.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1602391833977-358a52198938?auto=format&fit=crop&w=800&q=60",
  },
  price: 2900,
  location: "Ubud",
  country: "Indonesia",
  category: ["Pools", "Trending"],
},
{
  title: "Swiss Glass Dome",
  description: "Luxury dome offering panoramic mountain views and starry skies.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=60",
  },
  price: 2500,
  location: "Interlaken",
  country: "Switzerland",
  category: ["Domes", "Mountain"],
},
{
  title: "Machu Picchu Eco Cabin",
  description: "Stay close to one of the world's greatest wonders in a peaceful eco cabin.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=60",
  },
  price: 2200,
  location: "Cusco",
  country: "Peru",
  category: ["Mountain", "Camping"],
},
{
  title: "Lake Como Luxury Villa",
  description: "Elegant villa with private gardens and breathtaking lake views.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=60",
  },
  price: 5100,
  location: "Lake Como",
  country: "Italy",
  category: ["Pools", "Trending"],
},
{
  title: "Prague Castle Apartment",
  description: "Historic apartment located just steps from Prague Castle.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=60",
  },
  price: 2000,
  location: "Prague",
  country: "Czech Republic",
  category: ["Castles", "Iconic Cities"],
},
{
  title: "Himalayan Farm Cottage",
  description: "Experience organic farming and mountain life in a charming stone cottage.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1465379944081-7f47de8d74ac?auto=format&fit=crop&w=800&q=60",
  },
  price: 1400,
  location: "Shimla",
  country: "India",
  category: ["Farms", "Mountain"],
},
{
  title: "Cape Town Ocean Villa",
  description: "Modern villa overlooking the Atlantic Ocean with a stunning infinity pool.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=800&q=60",
  },
  price: 3600,
  location: "Cape Town",
  country: "South Africa",
  category: ["Pools", "Trending"],
},
{
  title: "Seaside Cliff Villa",
  description: "A luxurious cliffside villa with breathtaking ocean views and a private infinity pool.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=60",
  },
  price: 4200,
  location: "Amalfi Coast",
  country: "Italy",
  category: ["Pools", "Trending"],
},
{
  title: "Tokyo Skyline Loft",
  description: "Modern loft with panoramic views of Tokyo's dazzling skyline.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=60",
  },
  price: 2500,
  location: "Tokyo",
  country: "Japan",
  category: ["Iconic Cities", "Rooms"],
},
{
  title: "Snowy Alpine Chalet",
  description: "Classic wooden chalet nestled among snow-covered mountains.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=60",
  },
  price: 3300,
  location: "St. Moritz",
  country: "Switzerland",
  category: ["Mountain", "Trending"],
},
{
  title: "Marrakech Palace Stay",
  description: "A luxurious Moroccan palace with colorful interiors and tranquil courtyards.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
  },
  price: 2800,
  location: "Marrakech",
  country: "Morocco",
  category: ["Rooms", "Trending"],
},
{
  title: "Venice Grand Canal Suite",
  description: "Elegant suite overlooking Venice's famous Grand Canal.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=60",
  },
  price: 3100,
  location: "Venice",
  country: "Italy",
  category: ["Iconic Cities", "Rooms"],
},
{
  title: "Finnish Forest Cabin",
  description: "A cozy wooden cabin surrounded by pine forests and peaceful lakes.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
  },
  price: 1700,
  location: "Kuusamo",
  country: "Finland",
  category: ["Camping", "Mountain"],
},
{
  title: "Luxury Safari Camp",
  description: "Stay in luxury tents while enjoying unforgettable African wildlife safaris.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=800&q=60",
  },
  price: 3900,
  location: "Maasai Mara",
  country: "Kenya",
  category: ["Camping", "Trending"],
},
{
  title: "Lake Bled Cottage",
  description: "Peaceful lakeside cottage with postcard-perfect mountain scenery.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=60",
  },
  price: 1800,
  location: "Lake Bled",
  country: "Slovenia",
  category: ["Mountain", "Rooms"],
},
{
  title: "Iceland Ice Dome",
  description: "Sleep inside a luxury insulated dome beneath Iceland's star-filled skies.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=60",
  },
  price: 2800,
  location: "Akureyri",
  country: "Iceland",
  category: ["Domes", "Arctic"],
},
{
  title: "Greek Windmill House",
  description: "Unique windmill stay overlooking the blue Aegean Sea.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
  },
  price: 2400,
  location: "Mykonos",
  country: "Greece",
  category: ["Rooms", "Trending"],
},
{
  title: "Colorado River Cabin",
  description: "Rustic cabin beside a peaceful river with hiking and kayaking nearby.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=60",
  },
  price: 1600,
  location: "Colorado",
  country: "United States",
  category: ["Camping", "Mountain"],
},
{
  title: "Dubai Marina Apartment",
  description: "Stylish apartment with stunning marina views and luxury amenities.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=800&q=60",
  },
  price: 3400,
  location: "Dubai",
  country: "United Arab Emirates",
  category: ["Iconic Cities", "Rooms"],
},
{
  title: "Norway Fjord Glass House",
  description: "Modern glass home perched above breathtaking Norwegian fjords.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
  },
  price: 3700,
  location: "Geiranger",
  country: "Norway",
  category: ["Mountain", "Trending"],
},
{
  title: "Tuscan Olive Farm",
  description: "Experience authentic Italian countryside life surrounded by olive groves.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1465379944081-7f47de8d74ac?auto=format&fit=crop&w=800&q=60",
  },
  price: 1900,
  location: "Tuscany",
  country: "Italy",
  category: ["Farms", "Trending"],
},
{
  title: "Paris Luxury Penthouse",
  description: "Spacious penthouse with rooftop dining and Eiffel Tower views.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
  },
  price: 4700,
  location: "Paris",
  country: "France",
  category: ["Iconic Cities", "Trending"],
},
{
  title: "Scottish Castle Suite",
  description: "Sleep inside a centuries-old castle with luxurious royal suites.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1520637836862-4d197d17c35a?auto=format&fit=crop&w=800&q=60",
  },
  price: 5500,
  location: "Edinburgh",
  country: "United Kingdom",
  category: ["Castles", "Trending"],
},
{
  title: "Malibu Ocean House",
  description: "Beachfront home with private deck and spectacular Pacific sunsets.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=60",
  },
  price: 4500,
  location: "Malibu",
  country: "United States",
  category: ["Pools", "Trending"],
},
{
  title: "Hobbit Style Hillside Home",
  description: "A magical underground-style home inspired by fantasy architecture.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=60",
  },
  price: 1800,
  location: "Matamata",
  country: "New Zealand",
  category: ["Rooms", "Trending"],
},
{
  title: "Patagonia Mountain Lodge",
  description: "Luxury lodge surrounded by glaciers, lakes, and dramatic peaks.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=60",
  },
  price: 3200,
  location: "Patagonia",
  country: "Argentina",
  category: ["Mountain", "Camping"],
},
{
  title: "Luxury Yacht Stay",
  description: "Spend your vacation aboard a fully equipped luxury yacht in the Mediterranean.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=800&q=60",
  },
  price: 6500,
  location: "Monaco",
  country: "Monaco",
  category: ["Boats", "Trending"],
},
{
  title: "Santorini Sunset Villa",
  description: "Whitewashed villa perched on the cliffs with breathtaking sunset views over the Aegean Sea.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
  },
  price: 3900,
  location: "Santorini",
  country: "Greece",
  category: ["Pools", "Trending"],
},
{
  title: "Amsterdam Canal House",
  description: "Stay in a charming canal-side home in the heart of Amsterdam.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800&q=60",
  },
  price: 2200,
  location: "Amsterdam",
  country: "Netherlands",
  category: ["Iconic Cities", "Rooms"],
},
{
  title: "Swiss Lakeside Chalet",
  description: "Wake up to crystal-clear lakes and snow-capped mountains every morning.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=60",
  },
  price: 3400,
  location: "Lucerne",
  country: "Switzerland",
  category: ["Mountain", "Trending"],
},
{
  title: "Finnish Aurora Cabin",
  description: "Watch the Northern Lights from your warm glass-roof cabin.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=60",
  },
  price: 4200,
  location: "Rovaniemi",
  country: "Finland",
  category: ["Arctic", "Domes"],
},
{
  title: "Luxury Farmhouse Retreat",
  description: "Escape to rolling green fields and experience authentic countryside living.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1465379944081-7f47de8d74ac?auto=format&fit=crop&w=800&q=60",
  },
  price: 1700,
  location: "Punjab",
  country: "India",
  category: ["Farms", "Trending"],
},
{
  title: "Sydney Beach Apartment",
  description: "Modern apartment just steps away from Bondi Beach.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=60",
  },
  price: 2600,
  location: "Sydney",
  country: "Australia",
  category: ["Rooms", "Trending"],
},
{
  title: "Floating Cabin on Lake Bled",
  description: "A unique floating cabin surrounded by the beauty of Lake Bled.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=800&q=60",
  },
  price: 2900,
  location: "Lake Bled",
  country: "Slovenia",
  category: ["Boats", "Trending"],
},
{
  title: "Aspen Luxury Ski Resort",
  description: "Premium ski resort with direct slope access and cozy fireplaces.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=60",
  },
  price: 4600,
  location: "Aspen",
  country: "United States",
  category: ["Mountain", "Trending"],
},
{
  title: "London Heritage Apartment",
  description: "Classic apartment in central London close to famous landmarks.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=60",
  },
  price: 3100,
  location: "London",
  country: "United Kingdom",
  category: ["Iconic Cities", "Rooms"],
},
{
  title: "Iceland Glacier Dome",
  description: "Luxury dome stay overlooking glaciers and volcanic landscapes.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=60",
  },
  price: 3800,
  location: "Hofn",
  country: "Iceland",
  category: ["Domes", "Arctic"],
},
{
  title: "Rajasthan Royal Palace",
  description: "Experience royal living in a restored heritage palace.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=60",
  },
  price: 3600,
  location: "Jaipur",
  country: "India",
  category: ["Castles", "Trending"],
},
{
  title: "Costa Rica Rainforest Villa",
  description: "Luxury villa surrounded by lush rainforest and exotic wildlife.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=60",
  },
  price: 2500,
  location: "La Fortuna",
  country: "Costa Rica",
  category: ["Trending", "Pools"],
},
{
  title: "Dubai Palm Villa",
  description: "Exclusive beachfront villa located on the famous Palm Jumeirah.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=60",
  },
  price: 6400,
  location: "Dubai",
  country: "United Arab Emirates",
  category: ["Pools", "Trending"],
},
{
  title: "Prague Old Town Loft",
  description: "Historic loft apartment located in Prague's charming Old Town.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=60",
  },
  price: 2100,
  location: "Prague",
  country: "Czech Republic",
  category: ["Iconic Cities", "Rooms"],
},
{
  title: "Canadian Log Cabin",
  description: "Rustic log cabin surrounded by forests and peaceful lakes.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=60",
  },
  price: 1700,
  location: "Whistler",
  country: "Canada",
  category: ["Camping", "Mountain"],
},
{
  title: "Luxury Vineyard Estate",
  description: "Elegant estate with private wine tasting and scenic vineyard views.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1465379944081-7f47de8d74ac?auto=format&fit=crop&w=800&q=60",
  },
  price: 3200,
  location: "Bordeaux",
  country: "France",
  category: ["Farms", "Trending"],
},
{
  title: "Bali Bamboo House",
  description: "Eco-friendly bamboo home hidden among tropical rice fields.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1602391833977-358a52198938?auto=format&fit=crop&w=800&q=60",
  },
  price: 1800,
  location: "Ubud",
  country: "Indonesia",
  category: ["Trending", "Rooms"],
},
{
  title: "Norwegian Fishing Cabin",
  description: "Traditional waterfront cabin overlooking majestic Norwegian fjords.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
  },
  price: 2400,
  location: "Lofoten",
  country: "Norway",
  category: ["Boats", "Mountain"],
},
{
  title: "Maldives Private Island Villa",
  description: "Ultimate luxury on a private island with crystal-clear lagoons.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=800&q=60",
  },
  price: 9200,
  location: "Maldives",
  country: "Maldives",
  category: ["Pools", "Trending"],
},
{
  title: "New York Central Park Penthouse",
  description: "Luxury penthouse with panoramic views of Central Park and Manhattan skyline.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
  },
  price: 6800,
  location: "New York City",
  country: "United States",
  category: ["Iconic Cities", "Trending"],
},
];

module.exports = { data: sampleListings };